# Hyperparameters
START_AGE = 20
END_AGE = 100
RETIREMENT_AGE = 65
SURVIVAL_PROBABILITY = [0.99] * RETIREMENT_AGE + [0.8] * (END_AGE - RETIREMENT_AGE)
INCOME = [0.05] * RETIREMENT_AGE + [0.0] * (END_AGE - RETIREMENT_AGE)
AGE_LEVELS = list(range(START_AGE, END_AGE))

DELTA = 0.96
PSI = 0.1
GAMMA = 10

MIN_EQUITY = 0.2
initial_income = 1
income_volatility = 0.05
RISK_ASSET_AVERAGE_RETURN = 0.06
RISK_ASSET_VOLATILITY = 0.157
RISK_FREE_RETURN = 0.02
