import numpy as np

# Hyperparameters
START_AGE = 20
END_AGE = 100
RETIREMENT_AGE = 65
SURVIVAL_PROBABILITY = [0.99] * RETIREMENT_AGE + [0.8] * (END_AGE - RETIREMENT_AGE)
BASE_INCOME = 0.01
INCREASE = 0.03
INCOME = [BASE_INCOME * (1.0 + INCREASE) ** (n - 1) for n in range(1, RETIREMENT_AGE + 1)
    ] + [0.0] * (END_AGE - RETIREMENT_AGE)
AGE_LEVELS = list(range(START_AGE, END_AGE))
WEALTH_GRID = np.exp(np.linspace(-BASE_INCOME * 600, BASE_INCOME * 300, 30))

DELTA = 0.96
GAMMA = 4
PSI = 1 / GAMMA

MIN_EQUITY = 0.2
RISK_ASSET_AVERAGE_RETURN = 0.06
RISK_ASSET_VOLATILITY = 0.157
RISK_FREE_RETURN = 0.005


